import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

const loadImage = (url: string): Promise<string> => {
    return new Promise((resolve, reject) => {
        const img = new Image()
        img.crossOrigin = 'Anonymous'
        img.onload = () => {
            const canvas = document.createElement('canvas')
            canvas.width = img.width
            canvas.height = img.height
            const ctx = canvas.getContext('2d')
            ctx?.drawImage(img, 0, 0)
            resolve(canvas.toDataURL('image/png'))
        }
        img.onerror = reject
        img.src = url
    })
}

export const generateReceiptPDF = async (payment: any, action: 'download' | 'print' = 'download') => {
    const doc = new jsPDF()
    const brandingColor = payment.school?.primaryColor || '#667eea'
    const rgb = hexToRgb(brandingColor) || [102, 126, 234]

    // School Logo
    let headerY = 20
    if (payment.school?.logoUrl) {
        try {
            const logoBase64 = await loadImage(payment.school.logoUrl)
            doc.addImage(logoBase64, 'PNG', 105 - 15, 10, 30, 30, undefined, 'FAST')
            headerY = 45
        } catch (e) {
            console.error('Failed to load logo for PDF:', e)
        }
    }

    // School Header
    doc.setFontSize(22)
    doc.setTextColor(40, 44, 52)
    doc.text(payment.school?.name || 'Fee Due', 105, headerY, { align: 'center' })

    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.text(payment.school?.tagline || 'Official Payment Receipt', 105, headerY + 8, { align: 'center' })

    // Horizontal Line
    doc.setDrawColor(200)
    doc.line(20, headerY + 15, 190, headerY + 15)

    // Receipt Info
    doc.setFontSize(12)
    doc.setTextColor(0)
    doc.setFont('helvetica', 'bold')
    doc.text('Receipt Details', 20, headerY + 25)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    const receiptData = [
        ['Receipt No:', payment.receiptNumber || payment.transactionRef],
        ['Date:', new Date(payment.createdAt).toLocaleString()],
        ['Payment Method:', payment.method],
        ['Status:', payment.status],
    ]

    let y = headerY + 32
    receiptData.forEach(([label, value]) => {
        doc.text(label, 20, y)
        doc.text(value, 60, y)
        y += 7
    })

    // Student Info
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text('Student Information', 120, headerY + 25)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    const studentData = [
        ['Name:', `${payment.student?.firstName} ${payment.student?.lastName}`],
        ['Adm No:', payment.student?.admissionNumber],
        ['Class:', payment.student?.class?.name || 'N/A'],
    ]

    y = headerY + 32
    studentData.forEach(([label, value]) => {
        doc.text(label, 120, y)
        doc.text(value, 150, y)
        y += 7
    })

    // Transaction Table - Itemized breakdown
    const tableHead = [['Category', 'Description', 'Amount']]
    const tableBody: any[] = []

    if (payment.invoice?.items && payment.invoice.items.length > 0) {
        payment.invoice.items.forEach((item: any) => {
            if (!item.isDismissed) {
                tableBody.push([
                    item.category || 'OTHER',
                    item.description,
                    `KES ${parseFloat(item.amount).toLocaleString()}`
                ])
            }
        })
    } else {
        tableBody.push([
            'GENERAL',
            `Fee Payment - ${payment.invoice?.invoiceNumber || 'General'}`,
            `KES ${payment.amount.toLocaleString()}`
        ])
    }

    autoTable(doc, {
        startY: headerY + 65,
        head: tableHead,
        body: tableBody,
        foot: [['', 'Total Paid', `KES ${payment.amount.toLocaleString()}`]],
        theme: 'striped',
        headStyles: { fillColor: rgb as any },
        footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' }
    })

    // Footer
    const finalY = (doc as any).lastAutoTable?.finalY || 200
    doc.setFontSize(9)
    doc.setTextColor(150)
    doc.text('This is a computer-generated receipt and does not require a signature.', 105, finalY + 30, { align: 'center' })
    doc.text(`Generated by ${payment.school?.name || 'PayDesk'}`, 105, finalY + 35, { align: 'center' })

    if (action === 'print') {
        doc.autoPrint()
        window.open(doc.output('bloburl'), '_blank')
    } else {
        doc.save(`Receipt_${payment.receiptNumber || payment.transactionRef}.pdf`)
    }
}

export const generateInvoicePDF = async (invoice: any, action: 'download' | 'print' = 'download') => {
    const doc = new jsPDF()
    const brandingColor = invoice.school?.primaryColor || '#1f2937'
    const rgb = hexToRgb(brandingColor) || [31, 41, 55]

    // Logo
    let headerY = 20
    if (invoice.school?.logoUrl) {
        try {
            const logoBase64 = await loadImage(invoice.school.logoUrl)
            doc.addImage(logoBase64, 'PNG', 105 - 15, 10, 30, 30, undefined, 'FAST')
            headerY = 45
        } catch (e) {
            console.error('Failed to load logo for PDF:', e)
        }
    }

    doc.setFontSize(22)
    doc.setTextColor(40, 44, 52)
    doc.text(invoice.school?.name || 'Latest Fees', 105, headerY, { align: 'center' })

    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.text('OFFICIAL INVOICE', 105, headerY + 8, { align: 'center' })

    doc.setDrawColor(200)
    doc.line(20, headerY + 15, 190, headerY + 15)

    doc.setFontSize(12)
    doc.setTextColor(0)
    doc.setFont('helvetica', 'bold')
    doc.text('Invoice Details', 20, headerY + 25)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    const invData = [
        ['Invoice No:', invoice.invoiceNumber],
        ['Issue Date:', new Date(invoice.createdAt).toLocaleDateString()],
        ['Due Date:', new Date(invoice.dueDate).toLocaleDateString()],
        ['Status:', invoice.status.replace('_', ' ')],
    ]

    let y = headerY + 32
    invData.forEach(([label, value]) => {
        doc.text(label, 20, y)
        doc.text(value, 60, y)
        y += 7
    })

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text('Billed To', 120, headerY + 25)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    const studentData = [
        ['Name:', `${invoice.student?.firstName} ${invoice.student?.lastName}`],
        ['Adm No:', invoice.student?.admissionNumber],
        ['Term:', invoice.academicPeriod?.term || 'N/A'],
    ]

    y = headerY + 32
    studentData.forEach(([label, value]) => {
        doc.text(label, 120, y)
        doc.text(value, 150, y)
        y += 7
    })

    // Fetch billing summary for student context
    let previousArrears = 0
    let totalPaidToDate = 0
    try {
        const summaryRes = await fetch(`/api/students/${invoice.studentId}/billing-summary`)
        if (summaryRes.ok) {
            const summary = await summaryRes.json()
            totalPaidToDate = summary.totalPaid
            // Arrears = Overall Balance - This Invoice's remaining balance
            previousArrears = summary.overallBalance - parseFloat(invoice.balance.toString())
        }
    } catch (e) {
        console.error('Failed to fetch billing summary for PDF:', e)
    }

    const tableHead = [['Category', 'Description', 'Qty', 'Unit Price', 'Amount']]
    const tableBody: any[] = []

    if (invoice.items && invoice.items.length > 0) {
        invoice.items.forEach((item: any) => {
            if (!item.isDismissed) {
                const amount = parseFloat(item.amount)
                tableBody.push([
                    item.category || 'OTHER',
                    item.description,
                    item.quantity || 1,
                    `KES ${parseFloat(item.unitPrice || item.amount).toLocaleString()}`,
                    `KES ${amount.toLocaleString()}`
                ])
            }
        })
    } else {
        tableBody.push([
            'TUITION',
            invoice.feeStructure?.name || 'School Fees',
            1,
            `KES ${invoice.totalAmount.toLocaleString()}`,
            `KES ${invoice.totalAmount.toLocaleString()}`
        ])
    }

    autoTable(doc, {
        startY: headerY + 65,
        head: tableHead,
        body: tableBody,
        theme: 'grid',
        headStyles: { fillColor: rgb as any },
        styles: { fontSize: 9 }
    })

    const finalY = (doc as any).lastAutoTable?.finalY || 200

    // Summary Section
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)

    let summaryY = finalY + 15
    const drawSummaryLine = (label: string, amount: number, isBold = false, color = [0, 0, 0]) => {
        doc.setFont('helvetica', isBold ? 'bold' : 'normal')
        doc.setTextColor(color[0], color[1], color[2])
        doc.text(label, 130, summaryY)
        doc.text(`KES ${amount.toLocaleString()}`, 170, summaryY, { align: 'left' })
        summaryY += 7
    }

    drawSummaryLine('Current Invoice Total:', parseFloat(invoice.totalAmount.toString()))
    drawSummaryLine('Paid towards this Invoice:', parseFloat(invoice.paidAmount.toString()), false, [22, 163, 74])

    if (previousArrears !== 0) {
        drawSummaryLine(previousArrears > 0 ? 'Previous Arrears (B/F):' : 'Overpayment (B/F):', previousArrears, false, previousArrears > 0 ? [220, 38, 38] : [22, 163, 74])
    }

    doc.setDrawColor(200)
    doc.line(130, summaryY - 2, 195, summaryY - 2)
    summaryY += 3

    const totalOutstanding = previousArrears + parseFloat(invoice.balance.toString())
    drawSummaryLine('TOTAL OUTSTANDING:', totalOutstanding, true, totalOutstanding > 0 ? [220, 38, 38] : [22, 163, 74])

    doc.setTextColor(0)
    doc.setFontSize(11)
    doc.text('Payment Instructions:', 20, finalY + 40)
    doc.setFontSize(9)
    doc.text('1. Pay via M-Pesa Bill: 174379', 20, finalY + 47)
    doc.text(`2. Use Account No: ${invoice.invoiceNumber}`, 20, finalY + 52)
    doc.text('3. You can also pay directly via the PayDesk Portal.', 20, finalY + 57)

    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text('Thank you for choosing our institution.', 105, 285, { align: 'center' })

    if (action === 'print') {
        doc.autoPrint()
        window.open(doc.output('bloburl'), '_blank')
    } else {
        doc.save(`Invoice_${invoice.invoiceNumber}.pdf`)
    }
}

function hexToRgb(hex: string) {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
    return result ? [
        parseInt(result[1], 16),
        parseInt(result[2], 16),
        parseInt(result[3], 16)
    ] : null
}
